# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: 'target/*.jar'
    goals: 'install'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerACR'
    repository: 'springboothello'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'naresh-service-connection'
    appType: 'webAppContainer'
    WebAppName: 'springboothelloworld'
    deployToSlotOrASE: true
    ResourceGroupName: 'naresh-rg-demo'
    SlotName: 'production'
    DockerNamespace: 'naresh240.azurecr.io'
    DockerRepository: 'springboothello'
    DockerImageTag: 'latest'
